# Generated by Django 3.1.2 on 2020-10-21 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LotteryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('user_mail', models.EmailField(max_length=200)),
                ('has_been_diced', models.BooleanField(default=False)),
                ('who_hit', models.CharField(max_length=200)),
            ],
        ),
    ]
